baseurl = "/blog"   # allows http://example.com/blog and http://blog.example.com
title = "Alfonso R Reyes"
canonifyurls = true
relativeurls = true # allows http://example.com/blog and http://blog.example.com
paginate = 10
theme = "hyndman"
DisqusShortname = "fonzie-oilgains"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$", "external$"]
pluralizeListTitles = false
# local = false
buildFuture = true

[blackfriday]
hrefTargetBlank = true  # allows new tab on links


[params]

# Date format (refer to Go's date format: http://flippinggodateformat.com)
date_format = "2 January 2006"

# Number of posts to show on main page.
posts_count = 3

# Number of publications to show on main page.
pubs_count = 4
pubs_cover_count = 3

# Number of posts to show on main page.
portfolio_count = 4

# options for highlight.js (version, additional languages, and theme)
  highlightjsVersion = "9.12.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "tex"]
  highlightjsTheme = "github"

[[params.social]]
  icon = "envelope"
  icon_pack = "fa"
  link = "mailto:Alfonso.R.Reyes@gmail.com"
  text = "Alfonso.R.Reyes@gmail.com"

[[params.social]]
  icon = "twitter"
  icon_pack = "fa"
  link = "https://twitter.com/oilgains"
  text = "@oilgains"
  site = "Twitter"

[[params.social]]
  icon = "github-alt"
  icon_pack = "fa"
  link = "https://github.com/alfonsorreyes/"
  text = "alfonsorreyes"
  site = "GitHub"

[[params.social]]
  icon = "github"
  icon_pack = "fa"
  link = "https://github.com/f0nzie/"
  text = "f0nzie@OilGains"
  site = "GitHub"

[[params.social]]
  icon = "linkedin"
  icon_pack = "fa"
  link = "https://www.linkedin.com/in/alfonsorreyes"
  text = "Alfonso R Reyes on LinkedIn"



# Navigation Links
# The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 1

[[menu.main]]
  name = "Publications"
  url = "/publications/"
  weight = 2

[[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 3

[[menu.main]]
  name = "Portfolio"
  url = "/portfolio/"
  weight = 4


[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 6

